# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

controllers:
    resource:
        path: ../src/Adapter/Http/
        namespace: App\Adapter\Http
    type: attribute
